auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listings/create", views.create, name="create"),
    path("watchlist", views.watchlist, name="watchlist"),
    # path("import", views.import_categories, name="import_categories"),
    # path("listings/<int:li_id>", views.view_listing, name="view_listing"),
    path("listings/<int:li_id>/", views.view_listing, name="view_listing"),
    path("listings/<int:li_id>/comment/", views.comment_listing, name="comment_listing"),
    path("listings/<int:li_id>/bid/", views.bid_listing, name="bid_listing"),
    path("listings/<int:li_id>/close/", views.close_auction, name="close_auction"),
    path("listings/", views.index, name="listings"),
    path("category/<int:category_id>/", views.view_category, name="view_category"),
    path("category/", views.view_categories, name="view_categories"),
    path("mylistings/", views.my_listings, name="my_listings"),
    path("my-bid-listings/", views.my_bid_listings, name="my_bid_listings"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # API Routes
    path("emails", views.compose, name="compose"),
    path("emails/<int:email_id>", views.email, name="email"),
    path("emails/<str:mailbox>", views.mailbox, name="mailbox"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from datetime import datetime
from django.db.models import deletion
from django.db.models.aggregates import Max
from django.db.models.deletion import CASCADE
from django.db.models.fields import IntegerField
from django.db.models.fields.related import ForeignKey
from django.utils.timezone import now

from django.contrib.auth.models import User

# to update listing current_price field
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    pass

class ListingStatus(models.Model):
    status = models.CharField(max_length=16)
    description = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.status}"


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=300, blank=True)
    ebay_id = IntegerField()

    def calculateOpenListings(self):
        status = ListingStatus.objects.get(status='open')
        return Listing.objects.filter(category=self, status=status,).count()

    listings = property(calculateOpenListings)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField()
    startprice = models.FloatField()
    photo = models.ImageField(upload_to='images/', blank=True)
    status = models.ForeignKey(ListingStatus, default=4, on_delete=models.PROTECT, related_name="statuses")
    imageurl = models.URLField(blank=True)
    category = models.ForeignKey(Category, blank=True, on_delete=models.PROTECT, related_name="categories", default=1)
    creation_date = models.DateTimeField(default=now, editable=False)
    creator = models.ForeignKey(User, default=None, blank=True, on_delete=models.PROTECT, editable=True)
    current_price = models.FloatField(blank=True, default=0)
    
    """this return startprice """
    def copy_start_price(self):
        return self.startprice

    """this copy startprice to current_price on the listing creation """
    def save(self, *args, **kwargs):
        if not self.current_price:
            self.current_price = self.copy_start_price()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title


class Bid (models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    author = models.ForeignKey(User, default=None, blank=True, on_delete=models.PROTECT, editable=True, related_name="bidders")
    price = models.FloatField()
    date = models.DateTimeField(default=now, editable=False)
    def __str__(self):
        return f"{self.author.username} bid {self.price} to {self.listing.title}"

"""Update listing current_price on new bid save"""
@receiver(post_save, sender=Bid)
def update_listing_current_price(sender, instance, **kwargs):
    listing = Bid.objects.get(id=instance.id).listing
    listing.current_price = instance.price
    listing.save()

class Watchlist (models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    watcher = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.watcher.username} watching: {self.listing.title}"


class Comment (models.Model):
    listing = models.ForeignKey(Listing, blank=True, on_delete=models.CASCADE)
    text = models.TextField(max_length=500, default=None)
    date = models.DateTimeField(default=now, editable=False)
    author = ForeignKey(User, default=None, blank=True, on_delete=models.PROTECT, editable=True)
    def __str__(self):
        return f"{self.author.username} commented: {self.listing.title}"

auctions/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from .models import *

from django.forms import ModelForm

class CreateListingForm(ModelForm):
    class Meta:
        model = Listing
        # exclude = ('photo','creator', 'creation_date', 'status')
        fields = ('title', 'description', 'startprice', 'imageurl', 'category')
        # success_url = 'auctions:index'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows':'3'}),
            'startprice': forms.NumberInput(attrs={'class': 'form-control',}),
            'imageurl': forms.URLInput(attrs={'class': 'form-control',}),
            # 'category': forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name="name"),
            }
        # widgets = {
        # 'description': forms.Textarea(attrs={'class': 'form-control', 'cols': 80, 'rows': 20}),
        # }

class CommentListingForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        # exclude = ('author', 'date', 'listing')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows':'3'}),
            }

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ('price',)
        # exclude = ('author', 'date', 'listing')
        widgets = {
            'price': forms.NumberInput(attrs={'class': 'form-control',}),
            }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError, close_old_connections
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import CreateListingForm, CommentListingForm, BidForm

from .models import Comment, Bid, Category, Watchlist, ListingStatus, Listing, User
from . import utils
from django.contrib import messages



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        next = request.POST.get('next')
        if user is not None:
            login(request, user)
            if not next:
                return HttpResponseRedirect(reverse("auctions:index"))
            return HttpResponseRedirect(next) #redirect to next page
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password.",
                "next": next, #save redirect page in case wrong login
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        next = request.POST.get('next')

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match.",
                "next": next,
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken.",
                "next": next,
            })
        login(request, user)
        if not next:
            return HttpResponseRedirect(reverse("auctions:index"))
        return HttpResponseRedirect(next) #redirect to next page
    else:
        return render(request, "auctions/register.html")

"""Index page - view all open listings"""
def index(request):
    status = ListingStatus.objects.get(status='open')
    lis = Listing.objects.filter(status=status)

    return render(request, "auctions/index.html", {
                "lis": lis
            })


"""View Listing Item"""
def view_listing(request, li_id):
    """default props"""
    
    bid_message = None
    can_close = False

    """POST BID"""
    if request.method == "POST" and ('bid' in request.POST):
        bid_form = BidForm(request.POST)
        if bid_form.is_valid():
            """check maximum"""
            form_price = bid_form.cleaned_data['price']
            current_price = utils.get_current_price(li_id)

            if form_price <= current_price:
                bid_message = 'bid must be more than current price'
            else: 
                bid = bid_form.save(commit=False)

                """ add required parameters to bid"""
                bid.author = request.user
                bid.listing_id = li_id

                """saving to bids and Listing.current_price"""
                bid.save()

    """defaul view with no actions"""

    """Get listing item by ID"""
    li = Listing.objects.get(id=li_id)

    """Get Watchlist button status"""
    #check authentication status
    if request.user.is_authenticated:
        is_watched = Watchlist.objects.filter(listing_id=li_id, watcher=request.user)   
    else:
        is_watched = False

    """ Process Watching change requests (add to watchlist, unwatch) """
    if request.user.is_authenticated:
        watch = request.GET.get("watch", "")
        # adding to watchlist
        if watch == 'add':
            if not is_watched:
                add_watched = Watchlist(listing_id=li_id, watcher =request.user)
                add_watched.save()
                is_watched = add_watched
        # removing from watchlist
        if watch == 'remove':
            if is_watched:
                is_watched.delete()
    

    """Get Comments list"""
    comments = Comment.objects.filter(listing=li).order_by('-date')

    """Get bids for listing"""
    bids = Bid.objects.filter(listing=li)

    """Current price based on max bid and li.startprice"""
    current_price = utils.get_current_price(li_id)

    """Checks if your bid is current based on bid and request.user"""
    user = request.user
    your_bid_is_current = utils.get_your_bid_is_current(li_id, user)

    """checks if user can bid"""
    author = li.creator
    if request.user.is_authenticated:
        if request.user == author or li.status.status == 'closed':
            can_bid = False
        else:
            can_bid = True
    else:
        can_bid = False
    
    """checks if user is listing author and so can close the bid"""
    author = li.creator
    if request.user.is_authenticated:
        if request.user == author:
            can_close = True
        else:
            can_close = False

    """checks the winner"""
    
    if li.status.status == "closed":
        winner = utils.get_winner (li_id)
    else:
        winner = "No winner"

    
    """Props and render """
    props = {
        'li':li,
        'is_watched': is_watched,
        'comments': comments,
        "comment_form": CommentListingForm(instance=li),
        "bid_form": BidForm,
        "bids": bids,
        "current_price": current_price,
        "your_bid_is_current": your_bid_is_current,
        "can_bid": can_bid,
        "can_close": can_close,
        "winner": winner,
        "bid_message": bid_message,
        }

    return render(request, "auctions/listing.html", props)


"""POST Comment"""
def comment_listing(request, li_id):
    if request.method == "POST":
        comment_form = CommentListingForm(request.POST)
        # form = UserProfileEdit(instance=request.user)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.listing_id = li_id
            comment.save()
            redirect_path=reverse("auctions:view_listing", args=(li_id,))
            return HttpResponseRedirect(redirect_path)
    else:
        redirect_path=reverse("auctions:view_listing", args=(li_id,))
        return HttpResponseRedirect(redirect_path)

"""POST Bid"""
def bid_listing (request, li_id):
    if request.method == "POST":
        bid_form = BidForm(request.POST)
        if bid_form.is_valid():
            """check maximum"""
            form_price = bid_form.cleaned_data['price']
            current_price = utils.get_current_price(li_id)

            if form_price <= current_price:
                # bid_message = 'bid is to small'
                redirect_path=reverse("auctions:view_listing", args=(li_id, ))
                return HttpResponseRedirect(redirect_path)

            bid = bid_form.save(commit=False)

            """ add required parameters to bid"""
            bid.author = request.user
            bid.listing_id = li_id

            """saving to bids and Listing.current_price"""
            # try:
            bid.save()
            # except Exception as e: 
            #     print('Error on bid save:', e)
                # bid_error_message = 'bid_save_error'
            redirect_path=reverse("auctions:view_listing", args=(li_id, ))
            return HttpResponseRedirect(redirect_path)

            # else:
            #     Listing.objects.filter(id=li_id).update(current_price = form_price)
            
            redirect_path=reverse("auctions:view_listing", args=(li_id,))
            return HttpResponseRedirect(redirect_path)
    else:
        # redirect_path=reverse("auctions:view_listing", args=(li_id,))
        
        redirect_path=reverse("/", args=(li_id, ),)
        return HttpResponseRedirect(redirect_path)

"""Close Auction"""
def close_auction (request, li_id):
    if request.method == "POST":
        close_auction = request.POST['close_auction']
        if close_auction:
            """Update listing status"""
            li = Listing.objects.get(id=li_id)
            status = ListingStatus.objects.get(status="closed")
            li.status = status
            li.save()

            """redirect to listing page"""
            redirect_path=reverse("auctions:view_listing", args=(li_id, ))
            return HttpResponseRedirect(redirect_path)

            # li.winner = 

"""Create new listing"""
@login_required
def create(request):
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.creator = request.user
            instance.save()
            # messages.success(request, f'Listing Adde')
            return HttpResponseRedirect(reverse("auctions:index"))
        # else:
            # return render(request, "auctions/create.html", {"form": form})
    else:
        return render(request, "auctions/create.html", {"form": CreateListingForm})


"""View user's Watchlist"""
@login_required
def watchlist(request):
    status = ListingStatus.objects.get(id=4)
    user_id = request.user.id
    lis = Listing.objects.filter(status=status, watchlist__watcher=user_id)
    return render(request, "auctions/watchlist.html", {
                "lis": lis
            })


"""View user's created listings"""
@login_required

def my_listings(request):

auctions/templates/auctions/add.html
{% extends "auctions/layout.html" %} {% block body %}
<form method="post">
  {% csrf_token %} {{ form.as_table }}
  <input type="submit" value="Add" />
</form>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="shortcut icon" href="{%  static 'auctions/favicon.ico' %}">
        {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous"> {% endcomment %}
        <link href="{% static 'auctions/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start border-bottom">
            {% comment %} <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-2 border-bottom"> {% endcomment %}
                <a href="/" class="navbar-brand d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                {% comment %} <a href="/" class="navbar-brand d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none"> {% endcomment %}
                    <img class="bi me-2" style="height:50px;" src="{% static 'auctions/smile.svg.png' %}">
                    Auctions
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% comment %} <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"> {% endcomment %}
                <ul class="main-menu nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'auctions:index' %}" class="nav-link px-2 link-dark">Active Listings</a></li>
                    <li><a href="{% url 'auctions:view_categories' %}" class="nav-link px-2 link-dark">Categories</a></li>
                    <li><a href="{% url 'auctions:create' %}" class="nav-link px-2 link-dark">Create Listing</a></li>
                    <li><a href="{% url 'auctions:watchlist' %}" class="nav-link px-2 link-dark">Watchlist</a></li>
                    <li><a href="{% url 'auctions:my_listings' %}" class="nav-link px-2 link-dark">My Listings</a></li>
                    <li><a href="{% url 'auctions:my_bid_listings' %}" class="nav-link px-2 link-dark">My bids</a></li>
                    
                    
                </ul>
            
                <div class="col-md-3 text-end">
                    {% if user.is_authenticated %}
                        <small>Signed in as <strong>{{ user.username }} </strong></small>
                        <a type="button" class="btn btn-outline-primary me-2" href="{% url 'auctions:logout' %}">Sign out</a>
                    {% else %}
                        {% if request.GET.next %}
                            <a class="btn btn-outline-primary me-2" href="{% url 'auctions:login' %}?next={{ request.GET.next }}">Login</a>
                            <a class="btn btn-primary" href="{% url 'auctions:register' %}?next={{ request.GET.next }}">Register</a>
                        {% else %}
                            <a class="btn btn-outline-primary me-2" href="{% url 'auctions:login' %}?next={{ request.path }}">Login</a>
                            <a class="btn btn-primary" href="{% url 'auctions:register' %}?next={{ request.path }}">Register</a>
                        {% endif %}
                    {% endif %}
                </div>
            </header>
        </div>

        {% block body %}
        {% endblock %}

        <script src="{% static 'auctions/bootstrap.min.js' %}"></script>

        <script>
            const points = document.querySelectorAll(".main-menu li a");
            for(let point of points){
            if(point.href == document.location){
            point.style.textDecoration = "underline"
            }}
        </script>

    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% comment %} {% extends "auctions/button_watchlist.html" %} {% endcomment %}
{% load static %} 


{% block title %}
  Auctions - {{ li.title }}
{% endblock %}

{% block body %}
{% comment %} <h2>Active listings</h2> {% endcomment %}
<div class="main">
  <div class="album py-2 bg-light">
    <div class="container">
    
{% comment %} image {% endcomment %}
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-6">
            <div class="card-body">
              <h4 class="card-title">{{ li.title }}</h4>
                {% if li.imageurl %}
                  <img src="{{li.imageurl}}" class="card-img-top">
                {% else %}
                  <svg class="bd-placeholder-img" width="100%" height="250" xmlns="http://www.w3.org/2000/svg" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" role="img" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Изображение</text></svg>
                {% endif %}
            </div>
          </div>

          <div class="col-md-6">
            <div class="card-body">
            <div>
{% comment %} Price {% endcomment %}
            <div style="dislay:inline-block; float: left">
              {% if current_price %}
                <h3 style="display:inline" class="card-title pricing-card-title"> <small class="text-muted fw-light">$</small>{{ current_price }} </h3>
              {% endif %}
            </div style="dislay:inline-block;">

              <div style="dislay:inline-block; float: right" class="watch-button">
{% comment %} watchlist button {% endcomment %}
                {% if user.is_authenticated %}
                    {% if is_watched %}
                      <img src="{% static 'auctions/c5d445485e85.svg' %}">
                        <a style="text-align:right" class='watching_buttons' href="{% url 'auctions:view_listing' li.id %}?watch=remove">
                            <span style="text-align:right" class="bt_watching">Watching</span>
                            <span style="text-align:right" class="bt_unwatch">Unwatch</span>
                        </a>
                    {% else %}
                        <img src="{% static 'auctions/afb7b0b4bbec.svg' %}">
                        <a class='watching_buttons' href="{% url 'auctions:view_listing' li.id %}?watch=add">Add to Watchlist</a>
                    {% endif %}
                {% endif %} 
                </div>
            </div>


{% comment %} bids form {% endcomment %}
              {% if user.is_authenticated %}
                {% if can_bid and li.status.status == "open" %}
                  <p style="clear:both; color: red">{{ bid_message|default:'' }}</p>
                  <div style="clear:both" class="bid-form">
                    <form class="bid-form row g-3" method="post" action="{% url 'auctions:view_listing' li.id  %}">
                      {% csrf_token %} 
                      <div class="col-auto">
                        <label for="id_price" class="visually-hidden">{{ bid_form.price.label }}</label>
                        {{ bid_form.price }}
                      </div>
                      <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3" name='bid' value="Bid" >Bid</button>
                      </div>
                    </form>
                  </div>
                {% elif can_close and li.status.status == "open" %}
                  <div style="clear:both" class="close-auction-form">
                    <form class="close-auction-form row g-3" method="post" action="{% url 'auctions:close_auction' li.id  %}">
                    {% csrf_token %} 
                      <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3" name='close_auction' value="True" >Close Auction</button>
                      </div>
                    </form>
                  </div>
                {% endif %}
              {% else %}

                <div style="clear:both">
                  <p><a class="link" href="{% url 'auctions:login' %}?next={{ request.path }}">Log in</a> to bid</p>
                </div>
              {% endif %}

              {% comment %} <small class="text-muted fw-light">Start price: ${{ li.startprice }}</small> {% endcomment %}
              <div> <p style="clear:both" class="card-text">{{ li.description }}</p> </div>
              
              <!-- <p class="card-text"> Bid Status{{ li.status }}</p> -->
              <ul class="list-unstyled mt-3 mb-4">
                <li><small class="text-muted fw-light">Category: {{ li.category.name }}</small></li>
                <li><small class="text-muted fw-light">Created: {{ li.creation_date }} by {{ li.creator }}</small></li>
                {% comment %} <li>Category: {{ li.category.name }}</li> {% endcomment %}
                {% comment %} <li>Created: {{ li.creation_date }} by {{ li.creator }}</li> {% endcomment %}
              </ul>

{% comment %} number of bids {% endcomment %}
              {% if li.status.status == "open" %}
                  {% if bids %}
                      <span>Number of bids: </span> <span>{{ bids|length }}. </span>
                      {% if your_bid_is_current %}
                          <span>Your bid is current.</span>
                      {% endif %}
                  {% else %}
                      <span>No bids yet</span>
                  {% endif %}
              {% elif li.status.status == "closed" %}
                  {% if bids %}
                      <span>Number of bids: </span> <span>{{ bids|length }}</span>
                      {% if your_bid_is_current %}
                          <h3><span>You are the winner!</span></h3>
                      {% else %}
                          <h3><span>The winner is: {{ winner }}</span></h3>
                      {% endif %}
                  {% else %}
                      <span>Auction is closed, no bids.</span>
                  {% endif %}
              {% endif %}

{% comment %} bids form {% endcomment %}
              {% comment %} {% if user.is_authenticated %}
                {% if can_bid and li.status.status == "open" %}
                  <p><strong>{{ bid_message|default:'' }}</strong></p>
                  <div class="bid-form">
                    <form class="bid-form row g-3" method="post" action="{% url 'auctions:view_listing' li.id  %}">
                      {% csrf_token %} 
                      <div class="col-auto">
                        <label for="id_price" class="visually-hidden">{{ bid_form.price.label }}</label>
                        {{ bid_form.price }}
                      </div>
                      <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3" name='bid' value="Bid" >Bid</button>
                      </div>
                    </form>
                  </div>
                {% elif can_close and li.status.status == "open" %}
                  <div class="close-auction-form">
                    <form class="close-auction-form row g-3" method="post" action="{% url 'auctions:close_auction' li.id  %}">
                    {% csrf_token %} 
                      <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3" name='close_auction' value="True" >Close Auction</button>
                      </div>
                    </form>
                  </div>
                {% endif %}
              {% else %}
                <p><a class="link" href="{% url 'auctions:login' %}">Log in</a> to bid</p>
              {% endif %} {% endcomment %}
            </div>
          </div>
        </div>
      </div>

{% comment %} comments form {% endcomment %}
      {% if user.is_authenticated %}
            <div class="comments-form">
              <form method="post" action="{% url 'auctions:comment_listing' li.id  %}">
                {% csrf_token %} 
                <div class='mb-3'>
                {{ comment_form.text }}
                </div>
                <input class="form-control" type="submit" name='comment' value="Add Comment" />
              </form>
            </div>
      {% else %}
            <div class="comments-form">
                <div class='mb-3'>
                <p><a class="link" href="{% url 'auctions:login' %}?next={{ request.path }}">Log in</a> to comment</p>
                </div>
            </div>
      {% endif %}

{% comment %} comments {% endcomment %}
      {% for comment in comments %}
        <div class="card comments">
          <div class="card-header">
            {{ comment.author }}
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>{{ comment.text }}</p>
              <footer class="blockquote-footer">{{ comment.author }} <cite title="Date"> On {{ comment.date }}</cite></footer>
            </blockquote>
          </div>
        </div>
      {% empty %}
        <div class="card comments">
            <div class="card-header">
            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>No comments here yet.</p>
                <footer class="blockquote-footer"> You can be the first.<cite title="Date"></cite></footer>
              </blockquote>
            </div>
          </div>
      {% endfor %}

    </div>
  </div>
</div>
{% endblock %}